version: 2
registries:
  Artifactory:
    type: "npm-registry"
    url: "https://ghdevrel.jfrog.io/artifactory/api/npm/swampapp-npm/"
    token: "${{secrets.ARTIFACTORY_API_KEY}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
     - Artifactory
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
