version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      jfrog-artifactory:
        type: "npm-registry"
        url: "https://ghdevrel.jfrog.io/artifactory/swampapp-npm"
        username: "${{secrets.ARTIFACTORY_USERNAME}}"
        password: "${{secrets.ARTIFACTORY_PASSWORD}}"
