name: GitHub and JFrog Integration - Build App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read


jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ghjfintegration-docker-local
      NPM_REPO: ghjfintegrationapp-npm-remote
      IMAGE_NAME: ghjfintegrationapp
      JF_URL: https://${{ vars.JF_URL }}
      DOCKER_BUILD_SUMMARY: false
      DOCKER_BUILD_RECORD_UPLOAD: false
      # JFROG_CLI_LOG_LEVEL: DEBUG

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        oidc-provider-name: jfrog-github
        version: 2.67.0
      id: setup-cli
      env:
       JF_URL: https://${{ vars.JF_URL }}
       JF_PROJECT: ghjfintegration

    - name: Set JFrog CLI Config
      run: jf npm-config --global=true --repo-resolve=swampapp-npm --repo-deploy=swampapp-npm

    - name: build webapp
      run: |
         jf npm ci
         jf npm publish
         npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate Docker
      uses: docker/login-action@v3
      with:
         registry: ${{ vars.JF_URL }}
         username: ${{ steps.setup-cli.outputs.oidc-user }}
         password: ${{ steps.setup-cli.outputs.oidc-token }}

    - name: List files
      run: ls -la

    - name: List dist contents
      run: ls -la dist

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      id: build
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
        provenance: false

    - name: docker scan via JFrog 

      run: |
           jf docker pull ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest
           jf docker scan ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest --vuln --project=${{ vars.JF_PROJECT }} --fail=false

    - name: add docker package to build via JFrog 
      run: |
           echo "${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" > metadata.json
           jf rt build-docker-create ${{ env.DOCKER_REPO }} --image-file metadata.json
           
    - name: publish build info to JFrog 
      run: |
           jf rt build-collect-env
           jf rt build-add-git
           jf rt build-publish

    - name: JFrog build scan
      run: |
            jf build-scan --vuln --fail=false
